### ISSUE TITLE
setPassThruColor doesn't allow RGBW

### ISSUE THREAD

**Issue by Moustachauve** [aligator/NeoPixelBusGfx#2]
Usually, you can use setPassThruColor to force a color to be white with SK6812 like so:
```
Renderer<T_PIXEL_METHOD>::matrix->setPassThruColor(0xAA000000);
Renderer<T_PIXEL_METHOD>::matrix->fillScreen(0);
Renderer<T_PIXEL_METHOD>::matrix->setPassThruColor();
```

but NeoPixelBusGfx uses this code
```passThruFlag ? RgbColor(HtmlColor(passThruColor))  : RgbColor(HtmlColor(expandColor(color))));

Which could simply use RgbwColor instead of RgbColor to fix this.

**Comment by aligator** [comment]
Hi,

Thank you for the issue.
I looked into it, but it doesn't seem to be that easy.

You are right that it is not possible that this lib uses the passthrough value like the original lib. 
That's because the underlying lib is different and NeoPixelBus simply doesn't accept plain color values.  
It allways needs `typename T_COLOR_FEATURE::ColorObject` which basically just accepts values based on the used color feature and I cannot just use RgbwColor for because it doesn't compile with all possible ColorFeatures. (see: https://github.com/Makuna/NeoPixelBus/wiki/Color-objects - only RGB is usable by all)
So you are not able to set white explicitely.

Solution:
* To be able to pass a NeoPixelBus specific value I will try to add an overload which just accepts a color from NeoPixelBus:
```
setPassThruColor(typename T_COLOR_FEATURE::ColorObject c)
```
Then you would be able to use exactly the same colors as the NeoPixelBus allows for the used ColorFeature.
I think I will also deprecate the setPassThruColor(uint32_t c) because it is basically just a leftover from the original lib which is just not fully compatible with NeoPixelBus.

In the end the NeoPixelGfx doesn't seem to be really compatible to an extra white channel (as it uses only uint16_t internally). But the pasthrough would be a workaround for some cases, so I will add the overload.

What do you think? Do you have any further suggestions for better white compatibility?

**Comment by aligator** [comment]
Published a new version. (Edit: may take a while until it's public. You could use the git version until then...) 
Would you please test if it works with something like this?
```
Renderer<T_PIXEL_METHOD>::matrix->setPassThruColor(RgbwColor(0,0,0,170));
Renderer<T_PIXEL_METHOD>::matrix->fillScreen(0);
Renderer<T_PIXEL_METHOD>::matrix->setPassThruColor();
```

I have no leds with white channel so I could only test with RgbColor

**Comment by Moustachauve** [comment]
@aligator I just tested your new version, everything works as expected. I think its a great solution, I much rather use the Color objects than an int32
